// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA328cOcUnh1t_t4ebAgX34EpSQA_-t-jA',
    appId: '1:388649945103:web:5847b804d13e49ed047b7a',
    messagingSenderId: '388649945103',
    projectId: 'exampletest-be77e',
    authDomain: 'exampletest-be77e.firebaseapp.com',
    databaseURL: 'https://exampletest-be77e.firebaseio.com',
    storageBucket: 'exampletest-be77e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRwhvxsjt7UyG4zpHzRUitc4BLYxFuEhs',
    appId: '1:388649945103:android:df775a9adeb80f72047b7a',
    messagingSenderId: '388649945103',
    projectId: 'exampletest-be77e',
    databaseURL: 'https://exampletest-be77e.firebaseio.com',
    storageBucket: 'exampletest-be77e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9l7FKVfX0Tan4ynBSEFWXV4xQcPyqIlc',
    appId: '1:388649945103:ios:b86c0244918f2bf6047b7a',
    messagingSenderId: '388649945103',
    projectId: 'exampletest-be77e',
    databaseURL: 'https://exampletest-be77e.firebaseio.com',
    storageBucket: 'exampletest-be77e.firebasestorage.app',
    androidClientId: '388649945103-ghc7vahdnauqlveuo1i88b5mtsa7cep4.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9l7FKVfX0Tan4ynBSEFWXV4xQcPyqIlc',
    appId: '1:388649945103:ios:b86c0244918f2bf6047b7a',
    messagingSenderId: '388649945103',
    projectId: 'exampletest-be77e',
    databaseURL: 'https://exampletest-be77e.firebaseio.com',
    storageBucket: 'exampletest-be77e.firebasestorage.app',
    androidClientId: '388649945103-ghc7vahdnauqlveuo1i88b5mtsa7cep4.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA328cOcUnh1t_t4ebAgX34EpSQA_-t-jA',
    appId: '1:388649945103:web:85aaa4e67605f8e5047b7a',
    messagingSenderId: '388649945103',
    projectId: 'exampletest-be77e',
    authDomain: 'exampletest-be77e.firebaseapp.com',
    databaseURL: 'https://exampletest-be77e.firebaseio.com',
    storageBucket: 'exampletest-be77e.firebasestorage.app',
  );
}
